for retry_attempts in range(5):
    print(retry_attempts)